[project]
name = "litrevu-projet9"
version = "0.1.0"
description = "Student project"
authors = [
    {name = "Nels-j"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django (>=6.0.2,<7.0.0)",
    "pillow (>=12.2.0,<13.0.0)",
]

[tool.poetry]

[tool.poetry.group.dev.dependencies]
ruff = "^0.15.16"
mypy = "^2.1.0"
django-stubs = "^6.0.5"
django-debug-toolbar = "^6.3.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
plugins = ["mypy_django_plugin.main"]

[tool.django-stubs]
django_settings_module = "LITRevu.settings"
exclude = [
    "^\\.venv/",
    "^venv/",
    "^static/",
    "^media/",
]

[tool.ruff]
line-length = 88
target-version = "py313"
exclude = [
    ".venv",
    "venv",
    "node_modules",
    "static",
    "media",
]